# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actually < Formula
  desc "Cross-checks what your AI agent claims it did against what actually happened."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/actually"
  version "0.1.2+actually"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.2+actually/actually_0.1.2_darwin_amd64.tar.gz"
      sha256 "45b1cd390681dee13b0fb431b1976667854d7cc306c144618866475c426714fa"

      define_method(:install) do
        bin.install "actually"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.2+actually/actually_0.1.2_darwin_arm64.tar.gz"
      sha256 "63d92fd5049b3912094ad72936a9b6d1b77d989c2c18c3ad30daed9bcf773a00"

      define_method(:install) do
        bin.install "actually"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.2+actually/actually_0.1.2_linux_amd64.tar.gz"
      sha256 "865ce6bd235f600f5d81583eba2a677b8ad1c9a0358f58445245c28b2d49e67d"
      define_method(:install) do
        bin.install "actually"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.2+actually/actually_0.1.2_linux_arm64.tar.gz"
      sha256 "4413c109637752bcf88719edac5cd790553a5073e006e951abe3024b4b9f9032"
      define_method(:install) do
        bin.install "actually"
      end
    end
  end
end
