# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actually < Formula
  desc "Cross-checks what your AI agent claims it did against what actually happened."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/actually"
  version "0.1.3+actually"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.3+actually/actually_0.1.3_darwin_amd64.tar.gz"
      sha256 "e1313f8bb18084e8c12b60e8d59a927ddff857a63a8c2128b01aba7d82fe9a63"

      define_method(:install) do
        bin.install "actually"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.3+actually/actually_0.1.3_darwin_arm64.tar.gz"
      sha256 "42f72d54ad0ef4c538874f15f38940eaa3c129485219d7b13c1dae7e5a8dc0b7"

      define_method(:install) do
        bin.install "actually"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.3+actually/actually_0.1.3_linux_amd64.tar.gz"
      sha256 "4a449cb3cae6efa7585b3787b3ccef2db641b254574660ffdfb87d358748065d"
      define_method(:install) do
        bin.install "actually"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.3+actually/actually_0.1.3_linux_arm64.tar.gz"
      sha256 "9165a28020c764aebf437ac4f825b8c908e91923a151d932dbccc697fc92084a"
      define_method(:install) do
        bin.install "actually"
      end
    end
  end
end
