# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Actually < Formula
  desc "Cross-checks what your AI agent claims it did against what actually happened."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/actually"
  version "0.1.1+actually"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.1+actually/actually_0.1.1_darwin_amd64.tar.gz"
      sha256 "04158dac1950784979481262d54dc9c0aa881e7b34463aff8a453b448452ddfa"

      define_method(:install) do
        bin.install "actually"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.1+actually/actually_0.1.1_darwin_arm64.tar.gz"
      sha256 "624c3107f09cc011f3b708f3e0c45f819c7cf5a8e610cec93d5158cf72aed99a"

      define_method(:install) do
        bin.install "actually"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.1+actually/actually_0.1.1_linux_amd64.tar.gz"
      sha256 "29325c3c60d538ec82a9ba938bb908c81af4cc3443721457079125eb1b019b59"
      define_method(:install) do
        bin.install "actually"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.1+actually/actually_0.1.1_linux_arm64.tar.gz"
      sha256 "64229db7a1473839bd55b8d57e549c4b558f2d1d0e167fc986c35db244f1bb14"
      define_method(:install) do
        bin.install "actually"
      end
    end
  end
end
