# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkpoint < Formula
  desc "Automatic, zero-config git checkpoints before your AI agent touches anything."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/checkpoint"
  version "0.1.0+checkpoint"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0_darwin_amd64.tar.gz"
      sha256 "89ba37d76cbf9e7cc7b895d9a5b8457d6cbb790abb0e84f4072555905854e87e"

      define_method(:install) do
        bin.install "checkpoint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0_darwin_arm64.tar.gz"
      sha256 "8620fdbf3c799fdf95c66a06cc600ac5d2cbd587a28267dfb95f85a8dc32ac8f"

      define_method(:install) do
        bin.install "checkpoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0_linux_amd64.tar.gz"
      sha256 "bf5090bd5961d614e4d6dd529cd14b7de822dda05dadf96eec4a918c0d10b104"
      define_method(:install) do
        bin.install "checkpoint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0_linux_arm64.tar.gz"
      sha256 "211ec0d10a5fa9559f8fae961d1c35d131c117011027a95f9e6c3458e7bf99f3"
      define_method(:install) do
        bin.install "checkpoint"
      end
    end
  end
end
