# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkpoint < Formula
  desc "Automatic, zero-config git checkpoints before your AI agent touches anything."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/checkpoint"
  version "0.1.0+checkpoint"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0+checkpoint_darwin_amd64.tar.gz"
      sha256 "0f0c1897f274af863ec6369f3d0577cac4beaa87441d6a495884f4c5cab6e122"

      define_method(:install) do
        bin.install "checkpoint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0+checkpoint_darwin_arm64.tar.gz"
      sha256 "3b1a88003a50eaa0948ea348fc2eedeccfe880bd9975bf74fc7222b6e6431cf0"

      define_method(:install) do
        bin.install "checkpoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0+checkpoint_linux_amd64.tar.gz"
      sha256 "19205d4008155830d7d682c359c483bac43e6674732dfed7db868adde97d45df"
      define_method(:install) do
        bin.install "checkpoint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0+checkpoint_linux_arm64.tar.gz"
      sha256 "e72343e4b218fe18219caaf36dc9a520d9dde7313da3276656a8fe8d35e3e8fe"
      define_method(:install) do
        bin.install "checkpoint"
      end
    end
  end
end
