# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Checkpoint < Formula
  desc "Automatic, zero-config git checkpoints before your AI agent touches anything."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/checkpoint"
  version "0.1.0+checkpoint"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0+checkpoint_darwin_amd64.tar.gz"
      sha256 "a423f698d253ee5d24bff073036d7b025cbbe8d86a79933f0a7da82b105407b6"

      define_method(:install) do
        bin.install "checkpoint"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0+checkpoint_darwin_arm64.tar.gz"
      sha256 "48df70d1cfa8ebf12c41a3c01d2d7184992a65ce0d250ce90feef03c3aa6d28a"

      define_method(:install) do
        bin.install "checkpoint"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0+checkpoint_linux_amd64.tar.gz"
      sha256 "7ca2095b66068cbecde3f0cf7f82bdf0682c6b79387dc553c07b8c279d021055"
      define_method(:install) do
        bin.install "checkpoint"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+checkpoint/checkpoint_0.1.0+checkpoint_linux_arm64.tar.gz"
      sha256 "442e45d6f68e41d1c3cc3fd5a2c7930761294a2220dedb4d4ac6ee27337e3163"
      define_method(:install) do
        bin.install "checkpoint"
      end
    end
  end
end
