# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ctxmeter < Formula
  desc "A live context-window gauge for any AI coding CLI."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/ctxmeter"
  version "0.1.0+ctxmeter"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+ctxmeter/ctxmeter_0.1.0_darwin_amd64.tar.gz"
      sha256 "7d6781a5b60133309e40fe71bde4a20ede3dc71607e33095bd48b40cce781a9e"

      define_method(:install) do
        bin.install "ctxmeter"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+ctxmeter/ctxmeter_0.1.0_darwin_arm64.tar.gz"
      sha256 "9ad63a29a6e995f87bfe761215d006258f082bfe0b904b8e30566c6b5132e0ff"

      define_method(:install) do
        bin.install "ctxmeter"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+ctxmeter/ctxmeter_0.1.0_linux_amd64.tar.gz"
      sha256 "83cad53700f648788cac7ba01d32439e5ad32dd980374da0065c5bebc0b2448d"
      define_method(:install) do
        bin.install "ctxmeter"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+ctxmeter/ctxmeter_0.1.0_linux_arm64.tar.gz"
      sha256 "7c8b64966c048293c80e7d06474dd52dbf6740fd2df9692da7aece4a468f0c44"
      define_method(:install) do
        bin.install "ctxmeter"
      end
    end
  end
end
