# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Exists < Formula
  desc "Checks whether a package your AI agent just installed actually exists in the real registry."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/exists"
  version "0.1.0+exists"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+exists/exists_0.1.0_darwin_amd64.tar.gz"
      sha256 "ab2c5792c851cfe6584a9bdeeae6378a73f26df1e122b3e066d78d7e011bfb87"

      define_method(:install) do
        bin.install "exists"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+exists/exists_0.1.0_darwin_arm64.tar.gz"
      sha256 "65664407ee381d79bfecb096876358345ab3ba49ee2c7546d45bd9b635e72941"

      define_method(:install) do
        bin.install "exists"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+exists/exists_0.1.0_linux_amd64.tar.gz"
      sha256 "57871018f70e4a35e6b540b55cc2cc5b70c6169466d629b083f43568092d9ae8"
      define_method(:install) do
        bin.install "exists"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+exists/exists_0.1.0_linux_arm64.tar.gz"
      sha256 "9bbbf6a6397e910a624a704d8b3d950ac38eefa76b77a1d23dd7bca3075216b6"
      define_method(:install) do
        bin.install "exists"
      end
    end
  end
end
