# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Loopkill < Formula
  desc "Detects when your AI agent is stuck in a loop and interrupts it before it burns your quota."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/loopkill"
  version "0.1.0+loopkill"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+loopkill/loopkill_0.1.0_darwin_amd64.tar.gz"
      sha256 "e3fffbc8f40b6933e1fea48d181a524d360921468f432c81f1a22b2ef936fe90"

      define_method(:install) do
        bin.install "loopkill"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+loopkill/loopkill_0.1.0_darwin_arm64.tar.gz"
      sha256 "4af1cc8101843f4439fac2f5cab92798a75cfd21299887f6cf05b13ab0fb7bbf"

      define_method(:install) do
        bin.install "loopkill"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+loopkill/loopkill_0.1.0_linux_amd64.tar.gz"
      sha256 "f21570870edb8388aea56a737385d96f95bb7e088c0c7000684668864dc94f0b"
      define_method(:install) do
        bin.install "loopkill"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.0+loopkill/loopkill_0.1.0_linux_arm64.tar.gz"
      sha256 "4de5059c9597692d91c63dec8ea6a187cede88d6e990b2535ee14901cab364e4"
      define_method(:install) do
        bin.install "loopkill"
      end
    end
  end
end
