# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Permit < Formula
  desc "Makes Claude Code permission rules easy to write correctly and easy to diagnose."
  homepage "https://github.com/Soldsoul86/AAA/tree/main/permit"
  version "0.1.1+permit"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.1+permit/permit_0.1.1_darwin_amd64.tar.gz"
      sha256 "030c14a7db681043ed214b0c76c837a7d694b7219c686ce447f93758b1ad2040"

      define_method(:install) do
        bin.install "permit"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.1+permit/permit_0.1.1_darwin_arm64.tar.gz"
      sha256 "3d56ee74486f17938e49342ea7b16b004238eb88e0eb1949f8831fdc66eaea07"

      define_method(:install) do
        bin.install "permit"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.1+permit/permit_0.1.1_linux_amd64.tar.gz"
      sha256 "ae1d2d747f159e6807eb7d2185c1f3020d723799ab37e41564926f5ebceb17ea"
      define_method(:install) do
        bin.install "permit"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Soldsoul86/AAA/releases/download/v0.1.1+permit/permit_0.1.1_linux_arm64.tar.gz"
      sha256 "55ab6dafa418b18e9bc7aa106a269332760c68b8b4f56ab720b68a4fa3126f12"
      define_method(:install) do
        bin.install "permit"
      end
    end
  end
end
